
import java.awt.Color;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author my021
 */
public class GİRİŞ_EKRANI extends javax.swing.JFrame {

    /**
     * Creates new form GİRİŞ_EKRANI
     */
    public GİRİŞ_EKRANI() {
        initComponents();
        jPanel1.setBackground(new Color(0,0,0,160));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label3 = new java.awt.Label();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        kullanıcıadı = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        şifre = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        label3.setText("label1");

        jLabel4.setText("X");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("BLACKGYM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 260, 60));

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESİM/7bf00edd-1237-432f-8206-33378d604174.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        panel2.setBackground(new java.awt.Color(70, 70, 70));
        panel2.setForeground(new java.awt.Color(70, 70, 70));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Kullanıcı Adı");
        panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 150, 20));

        kullanıcıadı.setBackground(new java.awt.Color(70, 70, 70));
        kullanıcıadı.setForeground(new java.awt.Color(255, 255, 255));
        kullanıcıadı.setBorder(null);
        kullanıcıadı.setCaretColor(new java.awt.Color(255, 255, 255));
        kullanıcıadı.setSelectedTextColor(new java.awt.Color(73, 27, 80));
        panel2.add(kullanıcıadı, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 310, 30));

        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Şifre");
        panel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 100, 20));

        şifre.setBackground(new java.awt.Color(70, 70, 70));
        şifre.setForeground(new java.awt.Color(255, 255, 255));
        şifre.setBorder(null);
        şifre.setCaretColor(new java.awt.Color(255, 255, 255));
        şifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                şifreActionPerformed(evt);
            }
        });
        panel2.add(şifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 204, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 204, 0));
        jSeparator2.setOpaque(true);
        panel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 310, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 204, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 204, 0));
        jSeparator3.setOpaque(true);
        panel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 273, 310, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setForeground(new java.awt.Color(70, 70, 70));
        jButton1.setText("GİRİŞ");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 310, 40));

        jLabel5.setBackground(new java.awt.Color(255, 204, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 20, 30));

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 440, 504));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void şifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_şifreActionPerformed
        
    }//GEN-LAST:event_şifreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // kullanıcı adı ve şifre ile giriş yapma.
        String user = kullanıcıadı.getText();
        String password = şifre.getText();
        if(user.equals("mehmet")&& password.equals("123456")){
             EKRAN2 A1 = new EKRAN2();
        A1.setVisible(true);
        dispose();
        }
        else {
            Dikkat d1 = new Dikkat();
            d1.setVisible(true);
            dispose();
            
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GİRİŞ_EKRANI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GİRİŞ_EKRANI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GİRİŞ_EKRANI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GİRİŞ_EKRANI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GİRİŞ_EKRANI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField kullanıcıadı;
    private java.awt.Label label3;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JPasswordField şifre;
    // End of variables declaration//GEN-END:variables
}
