/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author my021
 */
public class SPORPROGRAM extends javax.swing.JFrame {

    /**
     * Creates new form SPORPROGRAM
     */
    public SPORPROGRAM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        textField36 = new java.awt.TextField();
        textField108 = new java.awt.TextField();
        textField109 = new java.awt.TextField();
        textField110 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        textField167 = new java.awt.TextField();
        textField168 = new java.awt.TextField();
        textField169 = new java.awt.TextField();
        textField170 = new java.awt.TextField();
        textField171 = new java.awt.TextField();
        textField172 = new java.awt.TextField();
        textField177 = new java.awt.TextField();
        textField193 = new java.awt.TextField();
        textField195 = new java.awt.TextField();
        textField200 = new java.awt.TextField();
        textField201 = new java.awt.TextField();
        textField204 = new java.awt.TextField();
        textField206 = new java.awt.TextField();
        textField207 = new java.awt.TextField();
        textField208 = new java.awt.TextField();
        textField210 = new java.awt.TextField();
        textField211 = new java.awt.TextField();
        textField212 = new java.awt.TextField();
        textField213 = new java.awt.TextField();
        textField214 = new java.awt.TextField();
        textField215 = new java.awt.TextField();
        textField216 = new java.awt.TextField();
        textField218 = new java.awt.TextField();
        textField221 = new java.awt.TextField();
        textField222 = new java.awt.TextField();
        textField224 = new java.awt.TextField();
        textField225 = new java.awt.TextField();
        textField226 = new java.awt.TextField();
        textField227 = new java.awt.TextField();
        textField228 = new java.awt.TextField();
        textField229 = new java.awt.TextField();
        textField230 = new java.awt.TextField();
        textField231 = new java.awt.TextField();
        textField234 = new java.awt.TextField();
        textField236 = new java.awt.TextField();
        textField237 = new java.awt.TextField();
        textField238 = new java.awt.TextField();
        textField239 = new java.awt.TextField();
        textField241 = new java.awt.TextField();
        textField242 = new java.awt.TextField();
        textField243 = new java.awt.TextField();
        textField248 = new java.awt.TextField();
        textField249 = new java.awt.TextField();
        textField250 = new java.awt.TextField();
        textField251 = new java.awt.TextField();
        textField252 = new java.awt.TextField();
        textField253 = new java.awt.TextField();
        textField254 = new java.awt.TextField();
        textField255 = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textField256 = new java.awt.TextField();
        textField232 = new java.awt.TextField();
        textField233 = new java.awt.TextField();
        textField209 = new java.awt.TextField();
        textField202 = new java.awt.TextField();
        textField111 = new java.awt.TextField();
        textField257 = new java.awt.TextField();
        textField235 = new java.awt.TextField();
        textField240 = new java.awt.TextField();
        textField217 = new java.awt.TextField();
        textField112 = new java.awt.TextField();
        textField244 = new java.awt.TextField();
        textField245 = new java.awt.TextField();
        textField258 = new java.awt.TextField();
        textField259 = new java.awt.TextField();
        textField246 = new java.awt.TextField();
        textField247 = new java.awt.TextField();
        textField260 = new java.awt.TextField();
        textField261 = new java.awt.TextField();
        textField262 = new java.awt.TextField();
        textField219 = new java.awt.TextField();
        textField113 = new java.awt.TextField();
        textField263 = new java.awt.TextField();
        textField264 = new java.awt.TextField();
        textField265 = new java.awt.TextField();
        textField266 = new java.awt.TextField();
        textField267 = new java.awt.TextField();
        textField223 = new java.awt.TextField();
        textField220 = new java.awt.TextField();
        textField268 = new java.awt.TextField();
        textField269 = new java.awt.TextField();
        textField270 = new java.awt.TextField();
        textField271 = new java.awt.TextField();
        textField272 = new java.awt.TextField();
        textField273 = new java.awt.TextField();
        textField274 = new java.awt.TextField();
        textField275 = new java.awt.TextField();
        textField276 = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(70, 70, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.setBackground(new java.awt.Color(255, 204, 0));
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(70, 70, 70));
        jTextField5.setText("             SALI");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 170, 50));

        jTextField6.setBackground(new java.awt.Color(255, 204, 0));
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(70, 70, 70));
        jTextField6.setText("            PAZAR");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 120, 170, 50));

        jTextField7.setBackground(new java.awt.Color(255, 204, 0));
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(70, 70, 70));
        jTextField7.setText("        PAZARTESİ");
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 170, 50));

        jTextField8.setBackground(new java.awt.Color(255, 204, 0));
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(70, 70, 70));
        jTextField8.setText("        ÇARŞAMBA");
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 170, 50));

        jTextField9.setBackground(new java.awt.Color(255, 204, 0));
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(70, 70, 70));
        jTextField9.setText("        PERŞEMBE");
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 170, 50));

        jTextField10.setBackground(new java.awt.Color(255, 204, 0));
        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(70, 70, 70));
        jTextField10.setText("            CUMA");
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 170, 50));

        jTextField11.setBackground(new java.awt.Color(255, 204, 0));
        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(70, 70, 70));
        jTextField11.setText("        CUMARTESİ");
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, 170, 50));

        textField36.setBackground(new java.awt.Color(255, 204, 0));
        textField36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField36.setForeground(new java.awt.Color(70, 70, 70));
        textField36.setName(""); // NOI18N
        textField36.setText("PULL DAY ");
        jPanel1.add(textField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 170, 30));

        textField108.setBackground(new java.awt.Color(70, 70, 70));
        textField108.setForeground(new java.awt.Color(255, 204, 0));
        textField108.setName(""); // NOI18N
        jPanel1.add(textField108, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 350, 170, 30));

        textField109.setBackground(new java.awt.Color(70, 70, 70));
        textField109.setForeground(new java.awt.Color(255, 204, 0));
        textField109.setName(""); // NOI18N
        jPanel1.add(textField109, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 410, 170, 30));

        textField110.setBackground(new java.awt.Color(70, 70, 70));
        textField110.setForeground(new java.awt.Color(255, 204, 0));
        textField110.setName(""); // NOI18N
        jPanel1.add(textField110, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 530, 170, 30));

        jLabel1.setBackground(new java.awt.Color(70, 70, 70));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("SPOR PROGRAMI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 310, 40));

        textField167.setBackground(new java.awt.Color(70, 70, 70));
        textField167.setForeground(new java.awt.Color(255, 204, 0));
        textField167.setName(""); // NOI18N
        jPanel1.add(textField167, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 380, 170, 30));

        textField168.setBackground(new java.awt.Color(70, 70, 70));
        textField168.setForeground(new java.awt.Color(255, 204, 0));
        textField168.setName(""); // NOI18N
        jPanel1.add(textField168, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 320, 170, 30));

        textField169.setBackground(new java.awt.Color(70, 70, 70));
        textField169.setForeground(new java.awt.Color(255, 204, 0));
        textField169.setName(""); // NOI18N
        jPanel1.add(textField169, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 290, 170, 30));

        textField170.setBackground(new java.awt.Color(70, 70, 70));
        textField170.setForeground(new java.awt.Color(255, 204, 0));
        textField170.setName(""); // NOI18N
        jPanel1.add(textField170, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 260, 170, 30));

        textField171.setBackground(new java.awt.Color(70, 70, 70));
        textField171.setForeground(new java.awt.Color(255, 204, 0));
        textField171.setName(""); // NOI18N
        jPanel1.add(textField171, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 230, 170, 30));

        textField172.setBackground(new java.awt.Color(70, 70, 70));
        textField172.setForeground(new java.awt.Color(255, 204, 0));
        textField172.setName(""); // NOI18N
        jPanel1.add(textField172, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 200, 170, 30));

        textField177.setBackground(new java.awt.Color(70, 70, 70));
        textField177.setForeground(new java.awt.Color(255, 204, 0));
        textField177.setName(""); // NOI18N
        textField177.setText("Bench Fly");
        jPanel1.add(textField177, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 170, 30));

        textField193.setBackground(new java.awt.Color(70, 70, 70));
        textField193.setForeground(new java.awt.Color(255, 204, 0));
        textField193.setName(""); // NOI18N
        textField193.setText("Shoulder Press");
        jPanel1.add(textField193, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 170, 30));

        textField195.setBackground(new java.awt.Color(70, 70, 70));
        textField195.setForeground(new java.awt.Color(255, 204, 0));
        textField195.setName(""); // NOI18N
        jPanel1.add(textField195, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 170, 30));

        textField200.setBackground(new java.awt.Color(255, 204, 0));
        textField200.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField200.setForeground(new java.awt.Color(70, 70, 70));
        textField200.setName(""); // NOI18N
        textField200.setText("UPPER BODY");
        jPanel1.add(textField200, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 170, 30));

        textField201.setBackground(new java.awt.Color(70, 70, 70));
        textField201.setForeground(new java.awt.Color(255, 204, 0));
        textField201.setName(""); // NOI18N
        jPanel1.add(textField201, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 170, 30));

        textField204.setBackground(new java.awt.Color(70, 70, 70));
        textField204.setForeground(new java.awt.Color(255, 204, 0));
        textField204.setName(""); // NOI18N
        jPanel1.add(textField204, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 170, 30));

        textField206.setBackground(new java.awt.Color(70, 70, 70));
        textField206.setForeground(new java.awt.Color(255, 204, 0));
        textField206.setName(""); // NOI18N
        jPanel1.add(textField206, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 170, 30));

        textField207.setBackground(new java.awt.Color(255, 204, 0));
        textField207.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField207.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField207.setForeground(new java.awt.Color(70, 70, 70));
        textField207.setName(""); // NOI18N
        textField207.setText("OFF DAY");
        jPanel1.add(textField207, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 170, 170, 30));

        textField208.setBackground(new java.awt.Color(70, 70, 70));
        textField208.setForeground(new java.awt.Color(255, 204, 0));
        textField208.setName(""); // NOI18N
        jPanel1.add(textField208, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 170, 30));

        textField210.setBackground(new java.awt.Color(70, 70, 70));
        textField210.setForeground(new java.awt.Color(255, 204, 0));
        textField210.setName(""); // NOI18N
        jPanel1.add(textField210, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 170, 30));

        textField211.setBackground(new java.awt.Color(70, 70, 70));
        textField211.setForeground(new java.awt.Color(255, 204, 0));
        textField211.setName(""); // NOI18N
        jPanel1.add(textField211, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 170, 30));

        textField212.setBackground(new java.awt.Color(70, 70, 70));
        textField212.setForeground(new java.awt.Color(255, 204, 0));
        textField212.setName(""); // NOI18N
        jPanel1.add(textField212, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 170, 30));

        textField213.setBackground(new java.awt.Color(70, 70, 70));
        textField213.setForeground(new java.awt.Color(255, 204, 0));
        textField213.setName(""); // NOI18N
        jPanel1.add(textField213, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 170, 30));

        textField214.setBackground(new java.awt.Color(70, 70, 70));
        textField214.setForeground(new java.awt.Color(255, 204, 0));
        textField214.setName(""); // NOI18N
        jPanel1.add(textField214, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 170, 30));

        textField215.setBackground(new java.awt.Color(70, 70, 70));
        textField215.setForeground(new java.awt.Color(255, 204, 0));
        textField215.setName(""); // NOI18N
        textField215.setText("Hanging Leg Raise");
        jPanel1.add(textField215, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 170, 30));

        textField216.setBackground(new java.awt.Color(70, 70, 70));
        textField216.setForeground(new java.awt.Color(255, 204, 0));
        textField216.setName(""); // NOI18N
        textField216.setText("Squat");
        jPanel1.add(textField216, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 170, 30));

        textField218.setBackground(new java.awt.Color(70, 70, 70));
        textField218.setForeground(new java.awt.Color(255, 204, 0));
        textField218.setName(""); // NOI18N
        jPanel1.add(textField218, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 170, 30));

        textField221.setBackground(new java.awt.Color(70, 70, 70));
        textField221.setForeground(new java.awt.Color(255, 204, 0));
        textField221.setName(""); // NOI18N
        textField221.setText("Cardio 30 min");
        jPanel1.add(textField221, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 170, 30));

        textField222.setBackground(new java.awt.Color(70, 70, 70));
        textField222.setForeground(new java.awt.Color(255, 204, 0));
        textField222.setName(""); // NOI18N
        textField222.setText("Smith Machine Calf Raise");
        jPanel1.add(textField222, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 170, 30));

        textField224.setBackground(new java.awt.Color(70, 70, 70));
        textField224.setForeground(new java.awt.Color(255, 204, 0));
        textField224.setName(""); // NOI18N
        textField224.setText("Leg Press");
        jPanel1.add(textField224, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 170, 30));

        textField225.setBackground(new java.awt.Color(70, 70, 70));
        textField225.setForeground(new java.awt.Color(255, 204, 0));
        textField225.setName(""); // NOI18N
        jPanel1.add(textField225, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 170, 30));

        textField226.setBackground(new java.awt.Color(70, 70, 70));
        textField226.setForeground(new java.awt.Color(255, 204, 0));
        textField226.setName(""); // NOI18N
        jPanel1.add(textField226, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 170, 30));

        textField227.setBackground(new java.awt.Color(255, 204, 0));
        textField227.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField227.setForeground(new java.awt.Color(70, 70, 70));
        textField227.setName(""); // NOI18N
        textField227.setText("LEG DAY + ABS");
        jPanel1.add(textField227, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 170, 30));

        textField228.setBackground(new java.awt.Color(70, 70, 70));
        textField228.setForeground(new java.awt.Color(255, 204, 0));
        textField228.setName(""); // NOI18N
        textField228.setText("Leg Extensions");
        jPanel1.add(textField228, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 170, 30));

        textField229.setBackground(new java.awt.Color(70, 70, 70));
        textField229.setForeground(new java.awt.Color(255, 204, 0));
        textField229.setName(""); // NOI18N
        textField229.setText("Skull Crushers");
        jPanel1.add(textField229, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 170, 30));

        textField230.setBackground(new java.awt.Color(70, 70, 70));
        textField230.setForeground(new java.awt.Color(255, 204, 0));
        textField230.setName(""); // NOI18N
        textField230.setText("Bench Press");
        jPanel1.add(textField230, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 170, 30));

        textField231.setBackground(new java.awt.Color(70, 70, 70));
        textField231.setForeground(new java.awt.Color(255, 204, 0));
        textField231.setName(""); // NOI18N
        textField231.setText("İncline Dumbbell Bench Press");
        jPanel1.add(textField231, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, 170, 30));

        textField234.setBackground(new java.awt.Color(70, 70, 70));
        textField234.setForeground(new java.awt.Color(255, 204, 0));
        textField234.setName(""); // NOI18N
        textField234.setText("Dambell Front Raise");
        jPanel1.add(textField234, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 170, 30));

        textField236.setBackground(new java.awt.Color(255, 204, 0));
        textField236.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField236.setForeground(new java.awt.Color(70, 70, 70));
        textField236.setName(""); // NOI18N
        textField236.setText("PUSH DAY");
        jPanel1.add(textField236, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 170, 30));

        textField237.setBackground(new java.awt.Color(70, 70, 70));
        textField237.setForeground(new java.awt.Color(255, 204, 0));
        textField237.setName(""); // NOI18N
        textField237.setText("Machine Fly");
        jPanel1.add(textField237, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 170, 30));

        textField238.setBackground(new java.awt.Color(70, 70, 70));
        textField238.setForeground(new java.awt.Color(255, 204, 0));
        textField238.setName(""); // NOI18N
        jPanel1.add(textField238, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 170, 30));

        textField239.setBackground(new java.awt.Color(70, 70, 70));
        textField239.setForeground(new java.awt.Color(255, 204, 0));
        textField239.setName(""); // NOI18N
        textField239.setText("Low Cable Row");
        jPanel1.add(textField239, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 170, 30));

        textField241.setBackground(new java.awt.Color(70, 70, 70));
        textField241.setForeground(new java.awt.Color(255, 204, 0));
        textField241.setName(""); // NOI18N
        textField241.setText("İncline Bench Press");
        jPanel1.add(textField241, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 170, 30));

        textField242.setBackground(new java.awt.Color(70, 70, 70));
        textField242.setForeground(new java.awt.Color(255, 204, 0));
        textField242.setName(""); // NOI18N
        textField242.setText("Lateral Raise");
        jPanel1.add(textField242, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 170, 30));

        textField243.setBackground(new java.awt.Color(70, 70, 70));
        textField243.setForeground(new java.awt.Color(255, 204, 0));
        textField243.setName(""); // NOI18N
        textField243.setText("Lat Pulldown");
        jPanel1.add(textField243, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 170, 30));

        textField248.setBackground(new java.awt.Color(70, 70, 70));
        textField248.setForeground(new java.awt.Color(255, 204, 0));
        textField248.setName(""); // NOI18N
        jPanel1.add(textField248, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 170, 30));

        textField249.setBackground(new java.awt.Color(70, 70, 70));
        textField249.setForeground(new java.awt.Color(255, 204, 0));
        textField249.setName(""); // NOI18N
        textField249.setText("21");
        jPanel1.add(textField249, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 170, 30));

        textField250.setBackground(new java.awt.Color(70, 70, 70));
        textField250.setForeground(new java.awt.Color(255, 204, 0));
        textField250.setName(""); // NOI18N
        textField250.setText("Dumbbell Hammer Curl");
        jPanel1.add(textField250, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 170, 30));

        textField251.setBackground(new java.awt.Color(70, 70, 70));
        textField251.setForeground(new java.awt.Color(255, 204, 0));
        textField251.setName(""); // NOI18N
        jPanel1.add(textField251, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 170, 30));

        textField252.setBackground(new java.awt.Color(70, 70, 70));
        textField252.setForeground(new java.awt.Color(255, 204, 0));
        textField252.setName(""); // NOI18N
        textField252.setText("Deadlift");
        jPanel1.add(textField252, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 170, 30));

        textField253.setBackground(new java.awt.Color(70, 70, 70));
        textField253.setForeground(new java.awt.Color(255, 204, 0));
        textField253.setName(""); // NOI18N
        textField253.setText("Barbell Row");
        jPanel1.add(textField253, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 170, 30));

        textField254.setBackground(new java.awt.Color(70, 70, 70));
        textField254.setForeground(new java.awt.Color(255, 204, 0));
        textField254.setName(""); // NOI18N
        textField254.setText("Face Pull");
        jPanel1.add(textField254, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 170, 30));

        textField255.setBackground(new java.awt.Color(70, 70, 70));
        textField255.setForeground(new java.awt.Color(255, 204, 0));
        textField255.setName(""); // NOI18N
        textField255.setText("Machine Shoulder Press");
        jPanel1.add(textField255, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 170, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESİM/icons8-back-30.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 60));

        jLabel3.setBackground(new java.awt.Color(70, 70, 70));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, 20, 40));

        textField256.setBackground(new java.awt.Color(70, 70, 70));
        textField256.setForeground(new java.awt.Color(255, 204, 0));
        textField256.setName(""); // NOI18N
        jPanel1.add(textField256, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 170, 30));

        textField232.setBackground(new java.awt.Color(70, 70, 70));
        textField232.setForeground(new java.awt.Color(255, 204, 0));
        textField232.setName(""); // NOI18N
        jPanel1.add(textField232, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 170, 30));

        textField233.setBackground(new java.awt.Color(70, 70, 70));
        textField233.setForeground(new java.awt.Color(255, 204, 0));
        textField233.setName(""); // NOI18N
        textField233.setText("Russian Twist");
        jPanel1.add(textField233, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 170, 30));

        textField209.setBackground(new java.awt.Color(70, 70, 70));
        textField209.setForeground(new java.awt.Color(255, 204, 0));
        textField209.setName(""); // NOI18N
        jPanel1.add(textField209, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 170, 30));

        textField202.setBackground(new java.awt.Color(70, 70, 70));
        textField202.setForeground(new java.awt.Color(255, 204, 0));
        textField202.setName(""); // NOI18N
        jPanel1.add(textField202, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 170, 30));

        textField111.setBackground(new java.awt.Color(70, 70, 70));
        textField111.setForeground(new java.awt.Color(255, 204, 0));
        textField111.setName(""); // NOI18N
        jPanel1.add(textField111, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 440, 170, 30));

        textField257.setBackground(new java.awt.Color(70, 70, 70));
        textField257.setForeground(new java.awt.Color(255, 204, 0));
        textField257.setName(""); // NOI18N
        jPanel1.add(textField257, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 170, 30));

        textField235.setBackground(new java.awt.Color(70, 70, 70));
        textField235.setForeground(new java.awt.Color(255, 204, 0));
        textField235.setName(""); // NOI18N
        textField235.setText("Triceps Pushdown");
        jPanel1.add(textField235, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 170, 30));

        textField240.setBackground(new java.awt.Color(70, 70, 70));
        textField240.setForeground(new java.awt.Color(255, 204, 0));
        textField240.setName(""); // NOI18N
        textField240.setText("Plank 60 second");
        jPanel1.add(textField240, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 170, 30));

        textField217.setBackground(new java.awt.Color(70, 70, 70));
        textField217.setForeground(new java.awt.Color(255, 204, 0));
        textField217.setName(""); // NOI18N
        jPanel1.add(textField217, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 170, 30));

        textField112.setBackground(new java.awt.Color(70, 70, 70));
        textField112.setForeground(new java.awt.Color(255, 204, 0));
        textField112.setName(""); // NOI18N
        jPanel1.add(textField112, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 470, 170, 30));

        textField244.setBackground(new java.awt.Color(70, 70, 70));
        textField244.setForeground(new java.awt.Color(255, 204, 0));
        textField244.setName(""); // NOI18N
        textField244.setText("Low Cable Row");
        jPanel1.add(textField244, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 170, 30));

        textField245.setBackground(new java.awt.Color(70, 70, 70));
        textField245.setForeground(new java.awt.Color(255, 204, 0));
        textField245.setName(""); // NOI18N
        textField245.setText("Lat Pulldown");
        jPanel1.add(textField245, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 170, 30));

        textField258.setBackground(new java.awt.Color(70, 70, 70));
        textField258.setForeground(new java.awt.Color(255, 204, 0));
        textField258.setName(""); // NOI18N
        textField258.setText("Baebell Row");
        jPanel1.add(textField258, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 170, 30));

        textField259.setBackground(new java.awt.Color(70, 70, 70));
        textField259.setForeground(new java.awt.Color(255, 204, 0));
        textField259.setName(""); // NOI18N
        textField259.setText("Deadlift");
        jPanel1.add(textField259, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 170, 30));

        textField246.setBackground(new java.awt.Color(70, 70, 70));
        textField246.setForeground(new java.awt.Color(255, 204, 0));
        textField246.setName(""); // NOI18N
        textField246.setText("Lateral Raise");
        jPanel1.add(textField246, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 170, 30));

        textField247.setBackground(new java.awt.Color(70, 70, 70));
        textField247.setForeground(new java.awt.Color(255, 204, 0));
        textField247.setName(""); // NOI18N
        textField247.setText("Dambell Front Raise");
        jPanel1.add(textField247, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 170, 30));

        textField260.setBackground(new java.awt.Color(70, 70, 70));
        textField260.setForeground(new java.awt.Color(255, 204, 0));
        textField260.setName(""); // NOI18N
        jPanel1.add(textField260, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 170, 30));

        textField261.setBackground(new java.awt.Color(70, 70, 70));
        textField261.setForeground(new java.awt.Color(255, 204, 0));
        textField261.setName(""); // NOI18N
        jPanel1.add(textField261, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 170, 30));

        textField262.setBackground(new java.awt.Color(70, 70, 70));
        textField262.setForeground(new java.awt.Color(255, 204, 0));
        textField262.setName(""); // NOI18N
        jPanel1.add(textField262, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 170, 30));

        textField219.setBackground(new java.awt.Color(70, 70, 70));
        textField219.setForeground(new java.awt.Color(255, 204, 0));
        textField219.setName(""); // NOI18N
        jPanel1.add(textField219, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 170, 30));

        textField113.setBackground(new java.awt.Color(70, 70, 70));
        textField113.setForeground(new java.awt.Color(255, 204, 0));
        textField113.setName(""); // NOI18N
        jPanel1.add(textField113, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 500, 170, 30));

        textField263.setBackground(new java.awt.Color(70, 70, 70));
        textField263.setForeground(new java.awt.Color(255, 204, 0));
        textField263.setName(""); // NOI18N
        textField263.setText("Bench Press");
        jPanel1.add(textField263, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 170, 30));

        textField264.setBackground(new java.awt.Color(70, 70, 70));
        textField264.setForeground(new java.awt.Color(255, 204, 0));
        textField264.setName(""); // NOI18N
        textField264.setText("İncline Dumbbell Bench Press");
        jPanel1.add(textField264, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 170, 30));

        textField265.setBackground(new java.awt.Color(255, 204, 0));
        textField265.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField265.setForeground(new java.awt.Color(70, 70, 70));
        textField265.setName(""); // NOI18N
        textField265.setText("LEG DAY + ABS");
        jPanel1.add(textField265, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 170, 170, 30));

        textField266.setBackground(new java.awt.Color(70, 70, 70));
        textField266.setForeground(new java.awt.Color(255, 204, 0));
        textField266.setName(""); // NOI18N
        textField266.setText("Leg Extensions");
        jPanel1.add(textField266, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 200, 170, 30));

        textField267.setBackground(new java.awt.Color(70, 70, 70));
        textField267.setForeground(new java.awt.Color(255, 204, 0));
        textField267.setName(""); // NOI18N
        textField267.setText("Leg Press");
        jPanel1.add(textField267, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, 170, 30));

        textField223.setBackground(new java.awt.Color(70, 70, 70));
        textField223.setForeground(new java.awt.Color(255, 204, 0));
        textField223.setName(""); // NOI18N
        textField223.setText("Smith Machine Calf Raise");
        jPanel1.add(textField223, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 260, 170, 30));

        textField220.setBackground(new java.awt.Color(70, 70, 70));
        textField220.setForeground(new java.awt.Color(255, 204, 0));
        textField220.setName(""); // NOI18N
        textField220.setText("Squat");
        jPanel1.add(textField220, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 290, 170, 30));

        textField268.setBackground(new java.awt.Color(70, 70, 70));
        textField268.setForeground(new java.awt.Color(255, 204, 0));
        textField268.setName(""); // NOI18N
        jPanel1.add(textField268, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 170, 30));

        textField269.setBackground(new java.awt.Color(70, 70, 70));
        textField269.setForeground(new java.awt.Color(255, 204, 0));
        textField269.setName(""); // NOI18N
        textField269.setText("Cardio 30 min");
        jPanel1.add(textField269, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 350, 170, 30));

        textField270.setBackground(new java.awt.Color(70, 70, 70));
        textField270.setForeground(new java.awt.Color(255, 204, 0));
        textField270.setName(""); // NOI18N
        jPanel1.add(textField270, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 380, 170, 30));

        textField271.setBackground(new java.awt.Color(70, 70, 70));
        textField271.setForeground(new java.awt.Color(255, 204, 0));
        textField271.setName(""); // NOI18N
        textField271.setText("Hanging Leg Raise");
        jPanel1.add(textField271, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 410, 170, 30));

        textField272.setBackground(new java.awt.Color(70, 70, 70));
        textField272.setForeground(new java.awt.Color(255, 204, 0));
        textField272.setName(""); // NOI18N
        textField272.setText("Russian Twist");
        jPanel1.add(textField272, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 440, 170, 30));

        textField273.setBackground(new java.awt.Color(70, 70, 70));
        textField273.setForeground(new java.awt.Color(255, 204, 0));
        textField273.setName(""); // NOI18N
        textField273.setText("Plank 60 second");
        jPanel1.add(textField273, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 470, 170, 30));

        textField274.setBackground(new java.awt.Color(70, 70, 70));
        textField274.setForeground(new java.awt.Color(255, 204, 0));
        textField274.setName(""); // NOI18N
        jPanel1.add(textField274, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, 170, 30));

        textField275.setBackground(new java.awt.Color(70, 70, 70));
        textField275.setForeground(new java.awt.Color(255, 204, 0));
        textField275.setName(""); // NOI18N
        jPanel1.add(textField275, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, 170, 30));

        textField276.setBackground(new java.awt.Color(255, 204, 0));
        textField276.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField276.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField276.setForeground(new java.awt.Color(70, 70, 70));
        textField276.setName(""); // NOI18N
        textField276.setText("OFF DAY");
        jPanel1.add(textField276, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 170, 30));

        jLabel4.setBackground(new java.awt.Color(70, 70, 70));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Ortopedik sakatlık geçmişiniz veya sakatlığınız varsa uzman bilgisi dahilinde çalışmalısınız.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 690, 580, 30));

        jLabel5.setBackground(new java.awt.Color(70, 70, 70));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("Programı istediğiniz gibi değiştirebilirsiniz .\n");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 280, 30));

        jLabel6.setBackground(new java.awt.Color(70, 70, 70));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("Başlangıç seviyesindeyseniz tekrar sayısını veya ağırlığı azaltıp çalışabilirsiniz.\n ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, 490, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESİM/icons8-information-20.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, 20, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESİM/icons8-information-20.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 20, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESİM/icons8-information-20.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 20, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESİM/icons8-information-20.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 20, 30));

        jLabel11.setBackground(new java.awt.Color(70, 70, 70));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 0));
        jLabel11.setText("Set ve tekrar sayısı 3 x 12  şeklindedir.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        //
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //
        EKRAN2 e4 = new EKRAN2();
        e4.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SPORPROGRAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SPORPROGRAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SPORPROGRAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SPORPROGRAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SPORPROGRAM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.TextField textField108;
    private java.awt.TextField textField109;
    private java.awt.TextField textField110;
    private java.awt.TextField textField111;
    private java.awt.TextField textField112;
    private java.awt.TextField textField113;
    private java.awt.TextField textField167;
    private java.awt.TextField textField168;
    private java.awt.TextField textField169;
    private java.awt.TextField textField170;
    private java.awt.TextField textField171;
    private java.awt.TextField textField172;
    private java.awt.TextField textField177;
    private java.awt.TextField textField193;
    private java.awt.TextField textField195;
    private java.awt.TextField textField200;
    private java.awt.TextField textField201;
    private java.awt.TextField textField202;
    private java.awt.TextField textField204;
    private java.awt.TextField textField206;
    private java.awt.TextField textField207;
    private java.awt.TextField textField208;
    private java.awt.TextField textField209;
    private java.awt.TextField textField210;
    private java.awt.TextField textField211;
    private java.awt.TextField textField212;
    private java.awt.TextField textField213;
    private java.awt.TextField textField214;
    private java.awt.TextField textField215;
    private java.awt.TextField textField216;
    private java.awt.TextField textField217;
    private java.awt.TextField textField218;
    private java.awt.TextField textField219;
    private java.awt.TextField textField220;
    private java.awt.TextField textField221;
    private java.awt.TextField textField222;
    private java.awt.TextField textField223;
    private java.awt.TextField textField224;
    private java.awt.TextField textField225;
    private java.awt.TextField textField226;
    private java.awt.TextField textField227;
    private java.awt.TextField textField228;
    private java.awt.TextField textField229;
    private java.awt.TextField textField230;
    private java.awt.TextField textField231;
    private java.awt.TextField textField232;
    private java.awt.TextField textField233;
    private java.awt.TextField textField234;
    private java.awt.TextField textField235;
    private java.awt.TextField textField236;
    private java.awt.TextField textField237;
    private java.awt.TextField textField238;
    private java.awt.TextField textField239;
    private java.awt.TextField textField240;
    private java.awt.TextField textField241;
    private java.awt.TextField textField242;
    private java.awt.TextField textField243;
    private java.awt.TextField textField244;
    private java.awt.TextField textField245;
    private java.awt.TextField textField246;
    private java.awt.TextField textField247;
    private java.awt.TextField textField248;
    private java.awt.TextField textField249;
    private java.awt.TextField textField250;
    private java.awt.TextField textField251;
    private java.awt.TextField textField252;
    private java.awt.TextField textField253;
    private java.awt.TextField textField254;
    private java.awt.TextField textField255;
    private java.awt.TextField textField256;
    private java.awt.TextField textField257;
    private java.awt.TextField textField258;
    private java.awt.TextField textField259;
    private java.awt.TextField textField260;
    private java.awt.TextField textField261;
    private java.awt.TextField textField262;
    private java.awt.TextField textField263;
    private java.awt.TextField textField264;
    private java.awt.TextField textField265;
    private java.awt.TextField textField266;
    private java.awt.TextField textField267;
    private java.awt.TextField textField268;
    private java.awt.TextField textField269;
    private java.awt.TextField textField270;
    private java.awt.TextField textField271;
    private java.awt.TextField textField272;
    private java.awt.TextField textField273;
    private java.awt.TextField textField274;
    private java.awt.TextField textField275;
    private java.awt.TextField textField276;
    private java.awt.TextField textField36;
    // End of variables declaration//GEN-END:variables
}
