/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author my021
 */
public class ÖRNEKDİYET extends javax.swing.JFrame {

    /**
     * Creates new form ÖRNEKDİYET
     */
    public ÖRNEKDİYET() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        textField36 = new java.awt.TextField();
        textField37 = new java.awt.TextField();
        textField119 = new java.awt.TextField();
        textField108 = new java.awt.TextField();
        textField109 = new java.awt.TextField();
        textField110 = new java.awt.TextField();
        textField111 = new java.awt.TextField();
        textField112 = new java.awt.TextField();
        textField113 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        textField167 = new java.awt.TextField();
        textField168 = new java.awt.TextField();
        textField169 = new java.awt.TextField();
        textField170 = new java.awt.TextField();
        textField171 = new java.awt.TextField();
        textField172 = new java.awt.TextField();
        textField173 = new java.awt.TextField();
        textField174 = new java.awt.TextField();
        textField175 = new java.awt.TextField();
        textField176 = new java.awt.TextField();
        textField177 = new java.awt.TextField();
        textField178 = new java.awt.TextField();
        textField179 = new java.awt.TextField();
        textField180 = new java.awt.TextField();
        textField181 = new java.awt.TextField();
        textField182 = new java.awt.TextField();
        textField183 = new java.awt.TextField();
        textField184 = new java.awt.TextField();
        textField185 = new java.awt.TextField();
        textField186 = new java.awt.TextField();
        textField187 = new java.awt.TextField();
        textField188 = new java.awt.TextField();
        textField189 = new java.awt.TextField();
        textField190 = new java.awt.TextField();
        textField191 = new java.awt.TextField();
        textField192 = new java.awt.TextField();
        textField193 = new java.awt.TextField();
        textField194 = new java.awt.TextField();
        textField195 = new java.awt.TextField();
        textField196 = new java.awt.TextField();
        textField197 = new java.awt.TextField();
        textField198 = new java.awt.TextField();
        textField199 = new java.awt.TextField();
        textField200 = new java.awt.TextField();
        textField201 = new java.awt.TextField();
        textField202 = new java.awt.TextField();
        textField203 = new java.awt.TextField();
        textField204 = new java.awt.TextField();
        textField205 = new java.awt.TextField();
        textField206 = new java.awt.TextField();
        textField207 = new java.awt.TextField();
        textField208 = new java.awt.TextField();
        textField209 = new java.awt.TextField();
        textField210 = new java.awt.TextField();
        textField211 = new java.awt.TextField();
        textField212 = new java.awt.TextField();
        textField213 = new java.awt.TextField();
        textField214 = new java.awt.TextField();
        textField215 = new java.awt.TextField();
        textField216 = new java.awt.TextField();
        textField217 = new java.awt.TextField();
        textField218 = new java.awt.TextField();
        textField219 = new java.awt.TextField();
        textField220 = new java.awt.TextField();
        textField221 = new java.awt.TextField();
        textField222 = new java.awt.TextField();
        textField223 = new java.awt.TextField();
        textField224 = new java.awt.TextField();
        textField225 = new java.awt.TextField();
        textField226 = new java.awt.TextField();
        textField227 = new java.awt.TextField();
        textField228 = new java.awt.TextField();
        textField229 = new java.awt.TextField();
        textField230 = new java.awt.TextField();
        textField231 = new java.awt.TextField();
        textField232 = new java.awt.TextField();
        textField233 = new java.awt.TextField();
        textField234 = new java.awt.TextField();
        textField235 = new java.awt.TextField();
        textField236 = new java.awt.TextField();
        textField237 = new java.awt.TextField();
        textField238 = new java.awt.TextField();
        textField239 = new java.awt.TextField();
        textField240 = new java.awt.TextField();
        textField241 = new java.awt.TextField();
        textField242 = new java.awt.TextField();
        textField243 = new java.awt.TextField();
        textField244 = new java.awt.TextField();
        textField245 = new java.awt.TextField();
        textField246 = new java.awt.TextField();
        textField247 = new java.awt.TextField();
        textField248 = new java.awt.TextField();
        textField249 = new java.awt.TextField();
        textField250 = new java.awt.TextField();
        textField251 = new java.awt.TextField();
        textField252 = new java.awt.TextField();
        textField253 = new java.awt.TextField();
        textField254 = new java.awt.TextField();
        textField255 = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(70, 70, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(255, 204, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(70, 70, 70));
        jTextField1.setText("    ARA ÖĞÜN");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 120, 60));

        jTextField3.setBackground(new java.awt.Color(255, 204, 0));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(70, 70, 70));
        jTextField3.setText("       AKŞAM");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 120, 120));

        jTextField4.setBackground(new java.awt.Color(255, 204, 0));
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(70, 70, 70));
        jTextField4.setText("      SABAH");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 120));

        jTextField5.setBackground(new java.awt.Color(255, 204, 0));
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(70, 70, 70));
        jTextField5.setText("             SALI");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 170, 50));

        jTextField6.setBackground(new java.awt.Color(255, 204, 0));
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(70, 70, 70));
        jTextField6.setText("            PAZAR");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 60, 170, 50));

        jTextField7.setBackground(new java.awt.Color(255, 204, 0));
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(70, 70, 70));
        jTextField7.setText("        PAZARTESİ");
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 170, 50));

        jTextField8.setBackground(new java.awt.Color(255, 204, 0));
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(70, 70, 70));
        jTextField8.setText("        ÇARŞAMBA");
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 170, 50));

        jTextField9.setBackground(new java.awt.Color(255, 204, 0));
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(70, 70, 70));
        jTextField9.setText("        PERŞEMBE");
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 170, 50));

        jTextField10.setBackground(new java.awt.Color(255, 204, 0));
        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(70, 70, 70));
        jTextField10.setText("            CUMA");
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 170, 50));

        jTextField11.setBackground(new java.awt.Color(255, 204, 0));
        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(70, 70, 70));
        jTextField11.setText("        CUMARTESİ");
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, 170, 50));

        jTextField12.setBackground(new java.awt.Color(255, 204, 0));
        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(70, 70, 70));
        jTextField12.setText("       ÖĞLE");
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 120, 120));

        textField36.setBackground(new java.awt.Color(70, 70, 70));
        textField36.setForeground(new java.awt.Color(255, 204, 0));
        textField36.setName(""); // NOI18N
        textField36.setText("2 Yumurta");
        textField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField36ActionPerformed(evt);
            }
        });
        jPanel1.add(textField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, 30));

        textField37.setBackground(new java.awt.Color(70, 70, 70));
        textField37.setForeground(new java.awt.Color(255, 204, 0));
        textField37.setName(""); // NOI18N
        jPanel1.add(textField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 500, 170, 30));

        textField119.setBackground(new java.awt.Color(70, 70, 70));
        textField119.setForeground(new java.awt.Color(255, 204, 0));
        textField119.setName(""); // NOI18N
        textField119.setText("2 yumurtalı sebzeli omlet");
        jPanel1.add(textField119, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 110, 170, 30));

        textField108.setBackground(new java.awt.Color(70, 70, 70));
        textField108.setForeground(new java.awt.Color(255, 204, 0));
        textField108.setName(""); // NOI18N
        jPanel1.add(textField108, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 290, 170, 30));

        textField109.setBackground(new java.awt.Color(70, 70, 70));
        textField109.setForeground(new java.awt.Color(255, 204, 0));
        textField109.setName(""); // NOI18N
        textField109.setText("Yeşil içecek");
        jPanel1.add(textField109, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 350, 170, 30));

        textField110.setBackground(new java.awt.Color(70, 70, 70));
        textField110.setForeground(new java.awt.Color(255, 204, 0));
        textField110.setName(""); // NOI18N
        jPanel1.add(textField110, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 380, 170, 30));

        textField111.setBackground(new java.awt.Color(70, 70, 70));
        textField111.setForeground(new java.awt.Color(255, 204, 0));
        textField111.setName(""); // NOI18N
        textField111.setText("Zerdeçallı enginar salatası");
        jPanel1.add(textField111, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 410, 170, 30));

        textField112.setBackground(new java.awt.Color(70, 70, 70));
        textField112.setForeground(new java.awt.Color(255, 204, 0));
        textField112.setName(""); // NOI18N
        jPanel1.add(textField112, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 440, 170, 30));

        textField113.setBackground(new java.awt.Color(70, 70, 70));
        textField113.setForeground(new java.awt.Color(255, 204, 0));
        textField113.setName(""); // NOI18N
        jPanel1.add(textField113, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 470, 170, 30));

        jLabel1.setBackground(new java.awt.Color(70, 70, 70));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("DİYET PROGRAMI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 310, 40));

        textField167.setBackground(new java.awt.Color(70, 70, 70));
        textField167.setForeground(new java.awt.Color(255, 204, 0));
        textField167.setName(""); // NOI18N
        jPanel1.add(textField167, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 320, 170, 30));

        textField168.setBackground(new java.awt.Color(70, 70, 70));
        textField168.setForeground(new java.awt.Color(255, 204, 0));
        textField168.setName(""); // NOI18N
        jPanel1.add(textField168, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 260, 170, 30));

        textField169.setBackground(new java.awt.Color(70, 70, 70));
        textField169.setForeground(new java.awt.Color(255, 204, 0));
        textField169.setName(""); // NOI18N
        textField169.setText(" 1 kase yoğurt");
        jPanel1.add(textField169, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 230, 170, 30));

        textField170.setBackground(new java.awt.Color(70, 70, 70));
        textField170.setForeground(new java.awt.Color(255, 204, 0));
        textField170.setName(""); // NOI18N
        jPanel1.add(textField170, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 200, 170, 30));

        textField171.setBackground(new java.awt.Color(70, 70, 70));
        textField171.setForeground(new java.awt.Color(255, 204, 0));
        textField171.setName(""); // NOI18N
        textField171.setText("1 dilim tam buğday  ekmek");
        jPanel1.add(textField171, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 170, 170, 30));

        textField172.setBackground(new java.awt.Color(70, 70, 70));
        textField172.setForeground(new java.awt.Color(255, 204, 0));
        textField172.setName(""); // NOI18N
        textField172.setText("Bol yeşillik");
        jPanel1.add(textField172, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 140, 170, 30));

        textField173.setBackground(new java.awt.Color(70, 70, 70));
        textField173.setForeground(new java.awt.Color(255, 204, 0));
        textField173.setName(""); // NOI18N
        jPanel1.add(textField173, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 500, 170, 30));

        textField174.setBackground(new java.awt.Color(70, 70, 70));
        textField174.setForeground(new java.awt.Color(255, 204, 0));
        textField174.setName(""); // NOI18N
        jPanel1.add(textField174, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 470, 170, 30));

        textField175.setBackground(new java.awt.Color(70, 70, 70));
        textField175.setForeground(new java.awt.Color(255, 204, 0));
        textField175.setName(""); // NOI18N
        jPanel1.add(textField175, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 440, 170, 30));

        textField176.setBackground(new java.awt.Color(70, 70, 70));
        textField176.setForeground(new java.awt.Color(255, 204, 0));
        textField176.setName(""); // NOI18N
        textField176.setText("Mantar sote + bol yeşillikli salata");
        jPanel1.add(textField176, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 410, 170, 30));

        textField177.setBackground(new java.awt.Color(70, 70, 70));
        textField177.setForeground(new java.awt.Color(255, 204, 0));
        textField177.setName(""); // NOI18N
        textField177.setText("Bitkisel süt ile kahve");
        jPanel1.add(textField177, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, 170, 30));

        textField178.setBackground(new java.awt.Color(70, 70, 70));
        textField178.setForeground(new java.awt.Color(255, 204, 0));
        textField178.setName(""); // NOI18N
        textField178.setText("20 g bitter çikolata");
        jPanel1.add(textField178, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 350, 170, 30));

        textField179.setBackground(new java.awt.Color(70, 70, 70));
        textField179.setForeground(new java.awt.Color(255, 204, 0));
        textField179.setName(""); // NOI18N
        jPanel1.add(textField179, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 320, 170, 30));

        textField180.setBackground(new java.awt.Color(70, 70, 70));
        textField180.setForeground(new java.awt.Color(255, 204, 0));
        textField180.setName(""); // NOI18N
        jPanel1.add(textField180, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 290, 170, 30));

        textField181.setBackground(new java.awt.Color(70, 70, 70));
        textField181.setForeground(new java.awt.Color(255, 204, 0));
        textField181.setName(""); // NOI18N
        jPanel1.add(textField181, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 260, 170, 30));

        textField182.setBackground(new java.awt.Color(70, 70, 70));
        textField182.setForeground(new java.awt.Color(255, 204, 0));
        textField182.setName(""); // NOI18N
        textField182.setText("Izgara tavuk ile salata");
        jPanel1.add(textField182, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, 170, 30));

        textField183.setBackground(new java.awt.Color(70, 70, 70));
        textField183.setForeground(new java.awt.Color(255, 204, 0));
        textField183.setName(""); // NOI18N
        jPanel1.add(textField183, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 200, 170, 30));

        textField184.setBackground(new java.awt.Color(70, 70, 70));
        textField184.setForeground(new java.awt.Color(255, 204, 0));
        textField184.setName(""); // NOI18N
        jPanel1.add(textField184, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 170, 30));

        textField185.setBackground(new java.awt.Color(70, 70, 70));
        textField185.setForeground(new java.awt.Color(255, 204, 0));
        textField185.setName(""); // NOI18N
        jPanel1.add(textField185, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 170, 30));

        textField186.setBackground(new java.awt.Color(70, 70, 70));
        textField186.setForeground(new java.awt.Color(255, 204, 0));
        textField186.setName(""); // NOI18N
        textField186.setText("1 kase yoğurt");
        jPanel1.add(textField186, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 170, 30));

        textField187.setBackground(new java.awt.Color(70, 70, 70));
        textField187.setForeground(new java.awt.Color(255, 204, 0));
        textField187.setName(""); // NOI18N
        jPanel1.add(textField187, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 500, 170, 30));

        textField188.setBackground(new java.awt.Color(70, 70, 70));
        textField188.setForeground(new java.awt.Color(255, 204, 0));
        textField188.setName(""); // NOI18N
        jPanel1.add(textField188, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, 170, 30));

        textField189.setBackground(new java.awt.Color(70, 70, 70));
        textField189.setForeground(new java.awt.Color(255, 204, 0));
        textField189.setName(""); // NOI18N
        textField189.setText("Bol yeşillikli salata");
        jPanel1.add(textField189, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, 170, 30));

        textField190.setBackground(new java.awt.Color(70, 70, 70));
        textField190.setForeground(new java.awt.Color(255, 204, 0));
        textField190.setName(""); // NOI18N
        textField190.setText("Izgara köfte (4 adet)");
        jPanel1.add(textField190, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 410, 170, 30));

        textField191.setBackground(new java.awt.Color(70, 70, 70));
        textField191.setForeground(new java.awt.Color(255, 204, 0));
        textField191.setName(""); // NOI18N
        jPanel1.add(textField191, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, 170, 30));

        textField192.setBackground(new java.awt.Color(70, 70, 70));
        textField192.setForeground(new java.awt.Color(255, 204, 0));
        textField192.setName(""); // NOI18N
        textField192.setText(" 1 küçük muz + 12 çiğ badem");
        jPanel1.add(textField192, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 350, 170, 30));

        textField193.setBackground(new java.awt.Color(70, 70, 70));
        textField193.setForeground(new java.awt.Color(255, 204, 0));
        textField193.setName(""); // NOI18N
        jPanel1.add(textField193, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 170, 30));

        textField194.setBackground(new java.awt.Color(70, 70, 70));
        textField194.setForeground(new java.awt.Color(255, 204, 0));
        textField194.setName(""); // NOI18N
        textField194.setText("50 g lor peynir");
        jPanel1.add(textField194, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 170, 30));

        textField195.setBackground(new java.awt.Color(70, 70, 70));
        textField195.setForeground(new java.awt.Color(255, 204, 0));
        textField195.setName(""); // NOI18N
        textField195.setText("Bol yeşillikli salata");
        jPanel1.add(textField195, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, 170, 30));

        textField196.setBackground(new java.awt.Color(70, 70, 70));
        textField196.setForeground(new java.awt.Color(255, 204, 0));
        textField196.setName(""); // NOI18N
        textField196.setText("Vicdan çorbası (sınırsız)");
        jPanel1.add(textField196, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 170, 30));

        textField197.setBackground(new java.awt.Color(70, 70, 70));
        textField197.setForeground(new java.awt.Color(255, 204, 0));
        textField197.setName(""); // NOI18N
        jPanel1.add(textField197, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 170, 30));

        textField198.setBackground(new java.awt.Color(70, 70, 70));
        textField198.setForeground(new java.awt.Color(255, 204, 0));
        textField198.setName(""); // NOI18N
        jPanel1.add(textField198, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 170, 30));

        textField199.setBackground(new java.awt.Color(70, 70, 70));
        textField199.setForeground(new java.awt.Color(255, 204, 0));
        textField199.setName(""); // NOI18N
        textField199.setText("1 dilim tam buğday ekmek");
        jPanel1.add(textField199, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 170, 30));

        textField200.setBackground(new java.awt.Color(70, 70, 70));
        textField200.setForeground(new java.awt.Color(255, 204, 0));
        textField200.setName(""); // NOI18N
        textField200.setText("1 yumurta + 3 ceviz");
        jPanel1.add(textField200, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 170, 30));

        textField201.setBackground(new java.awt.Color(70, 70, 70));
        textField201.setForeground(new java.awt.Color(255, 204, 0));
        textField201.setName(""); // NOI18N
        jPanel1.add(textField201, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 170, 30));

        textField202.setBackground(new java.awt.Color(70, 70, 70));
        textField202.setForeground(new java.awt.Color(255, 204, 0));
        textField202.setName(""); // NOI18N
        textField202.setText("2 adet zeytinyağlı enginar");
        jPanel1.add(textField202, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 170, 30));

        textField203.setBackground(new java.awt.Color(70, 70, 70));
        textField203.setForeground(new java.awt.Color(255, 204, 0));
        textField203.setName(""); // NOI18N
        jPanel1.add(textField203, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 170, 30));

        textField204.setBackground(new java.awt.Color(70, 70, 70));
        textField204.setForeground(new java.awt.Color(255, 204, 0));
        textField204.setName(""); // NOI18N
        jPanel1.add(textField204, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 170, 30));

        textField205.setBackground(new java.awt.Color(70, 70, 70));
        textField205.setForeground(new java.awt.Color(255, 204, 0));
        textField205.setName(""); // NOI18N
        jPanel1.add(textField205, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 170, 30));

        textField206.setBackground(new java.awt.Color(70, 70, 70));
        textField206.setForeground(new java.awt.Color(255, 204, 0));
        textField206.setName(""); // NOI18N
        jPanel1.add(textField206, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 170, 30));

        textField207.setBackground(new java.awt.Color(70, 70, 70));
        textField207.setForeground(new java.awt.Color(255, 204, 0));
        textField207.setName(""); // NOI18N
        textField207.setText("1 bardak süt");
        jPanel1.add(textField207, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 170, 30));

        textField208.setBackground(new java.awt.Color(70, 70, 70));
        textField208.setForeground(new java.awt.Color(255, 204, 0));
        textField208.setName(""); // NOI18N
        jPanel1.add(textField208, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 170, 30));

        textField209.setBackground(new java.awt.Color(70, 70, 70));
        textField209.setForeground(new java.awt.Color(255, 204, 0));
        textField209.setName(""); // NOI18N
        jPanel1.add(textField209, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 170, 30));

        textField210.setBackground(new java.awt.Color(70, 70, 70));
        textField210.setForeground(new java.awt.Color(255, 204, 0));
        textField210.setName(""); // NOI18N
        jPanel1.add(textField210, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 170, 30));

        textField211.setBackground(new java.awt.Color(70, 70, 70));
        textField211.setForeground(new java.awt.Color(255, 204, 0));
        textField211.setName(""); // NOI18N
        jPanel1.add(textField211, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 170, 30));

        textField212.setBackground(new java.awt.Color(70, 70, 70));
        textField212.setForeground(new java.awt.Color(255, 204, 0));
        textField212.setName(""); // NOI18N
        textField212.setText("2 kuru kayısı + 2 ceviz");
        jPanel1.add(textField212, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 170, 30));

        textField213.setBackground(new java.awt.Color(70, 70, 70));
        textField213.setForeground(new java.awt.Color(255, 204, 0));
        textField213.setName(""); // NOI18N
        textField213.setText("Ton balıklı salata");
        jPanel1.add(textField213, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 170, 30));

        textField214.setBackground(new java.awt.Color(70, 70, 70));
        textField214.setForeground(new java.awt.Color(255, 204, 0));
        textField214.setName(""); // NOI18N
        jPanel1.add(textField214, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 170, 30));

        textField215.setBackground(new java.awt.Color(70, 70, 70));
        textField215.setForeground(new java.awt.Color(255, 204, 0));
        textField215.setName(""); // NOI18N
        textField215.setText("2 adet yulaflı kurabiye");
        jPanel1.add(textField215, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 170, 30));

        textField216.setBackground(new java.awt.Color(70, 70, 70));
        textField216.setForeground(new java.awt.Color(255, 204, 0));
        textField216.setName(""); // NOI18N
        textField216.setText("Vicdan Çorbası (sınırsız)");
        jPanel1.add(textField216, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 170, 30));

        textField217.setBackground(new java.awt.Color(70, 70, 70));
        textField217.setForeground(new java.awt.Color(255, 204, 0));
        textField217.setName(""); // NOI18N
        jPanel1.add(textField217, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 170, 30));

        textField218.setBackground(new java.awt.Color(70, 70, 70));
        textField218.setForeground(new java.awt.Color(255, 204, 0));
        textField218.setName(""); // NOI18N
        textField218.setText("Bol Yeşillikli Salata");
        jPanel1.add(textField218, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 170, 30));

        textField219.setBackground(new java.awt.Color(70, 70, 70));
        textField219.setForeground(new java.awt.Color(255, 204, 0));
        textField219.setName(""); // NOI18N
        textField219.setText("Mercimekli karabuğdaylı salata");
        jPanel1.add(textField219, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 170, 30));

        textField220.setBackground(new java.awt.Color(70, 70, 70));
        textField220.setForeground(new java.awt.Color(255, 204, 0));
        textField220.setName(""); // NOI18N
        jPanel1.add(textField220, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 170, 30));

        textField221.setBackground(new java.awt.Color(70, 70, 70));
        textField221.setForeground(new java.awt.Color(255, 204, 0));
        textField221.setName(""); // NOI18N
        textField221.setText("50 gram lor peynir");
        jPanel1.add(textField221, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 170, 30));

        textField222.setBackground(new java.awt.Color(70, 70, 70));
        textField222.setForeground(new java.awt.Color(255, 204, 0));
        textField222.setName(""); // NOI18N
        textField222.setText("7-8 adet zeytin");
        jPanel1.add(textField222, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 170, 30));

        textField223.setBackground(new java.awt.Color(70, 70, 70));
        textField223.setForeground(new java.awt.Color(255, 204, 0));
        textField223.setName(""); // NOI18N
        jPanel1.add(textField223, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 170, 30));

        textField224.setBackground(new java.awt.Color(70, 70, 70));
        textField224.setForeground(new java.awt.Color(255, 204, 0));
        textField224.setName(""); // NOI18N
        textField224.setText("Bol yeşillik");
        jPanel1.add(textField224, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 170, 30));

        textField225.setBackground(new java.awt.Color(70, 70, 70));
        textField225.setForeground(new java.awt.Color(255, 204, 0));
        textField225.setName(""); // NOI18N
        jPanel1.add(textField225, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 170, 30));

        textField226.setBackground(new java.awt.Color(70, 70, 70));
        textField226.setForeground(new java.awt.Color(255, 204, 0));
        textField226.setName(""); // NOI18N
        jPanel1.add(textField226, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 170, 30));

        textField227.setBackground(new java.awt.Color(70, 70, 70));
        textField227.setForeground(new java.awt.Color(255, 204, 0));
        textField227.setName(""); // NOI18N
        textField227.setText("1 dilim peynir");
        jPanel1.add(textField227, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 170, 30));

        textField228.setBackground(new java.awt.Color(70, 70, 70));
        textField228.setForeground(new java.awt.Color(255, 204, 0));
        textField228.setName(""); // NOI18N
        textField228.setText("1 dilim tam buğday ekmek");
        jPanel1.add(textField228, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 170, 30));

        textField229.setBackground(new java.awt.Color(70, 70, 70));
        textField229.setForeground(new java.awt.Color(255, 204, 0));
        textField229.setName(""); // NOI18N
        textField229.setText("2 ceviz");
        jPanel1.add(textField229, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 170, 30));

        textField230.setBackground(new java.awt.Color(70, 70, 70));
        textField230.setForeground(new java.awt.Color(255, 204, 0));
        textField230.setName(""); // NOI18N
        textField230.setText("1 kase yoğurt");
        jPanel1.add(textField230, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 170, 30));

        textField231.setBackground(new java.awt.Color(70, 70, 70));
        textField231.setForeground(new java.awt.Color(255, 204, 0));
        textField231.setName(""); // NOI18N
        jPanel1.add(textField231, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 170, 30));

        textField232.setBackground(new java.awt.Color(70, 70, 70));
        textField232.setForeground(new java.awt.Color(255, 204, 0));
        textField232.setName(""); // NOI18N
        textField232.setText("Izgara somon");
        jPanel1.add(textField232, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 170, 30));

        textField233.setBackground(new java.awt.Color(70, 70, 70));
        textField233.setForeground(new java.awt.Color(255, 204, 0));
        textField233.setName(""); // NOI18N
        textField233.setText("Buharda sebze");
        jPanel1.add(textField233, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 170, 30));

        textField234.setBackground(new java.awt.Color(70, 70, 70));
        textField234.setForeground(new java.awt.Color(255, 204, 0));
        textField234.setName(""); // NOI18N
        textField234.setText("Tarçın");
        jPanel1.add(textField234, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 170, 30));

        textField235.setBackground(new java.awt.Color(70, 70, 70));
        textField235.setForeground(new java.awt.Color(255, 204, 0));
        textField235.setName(""); // NOI18N
        jPanel1.add(textField235, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 170, 30));

        textField236.setBackground(new java.awt.Color(70, 70, 70));
        textField236.setForeground(new java.awt.Color(255, 204, 0));
        textField236.setName(""); // NOI18N
        textField236.setText("1 kase yoğurt / 1 bardak süt");
        jPanel1.add(textField236, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 170, 30));

        textField237.setBackground(new java.awt.Color(70, 70, 70));
        textField237.setForeground(new java.awt.Color(255, 204, 0));
        textField237.setName(""); // NOI18N
        textField237.setText("2 kuru kayısı");
        jPanel1.add(textField237, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 170, 30));

        textField238.setBackground(new java.awt.Color(70, 70, 70));
        textField238.setForeground(new java.awt.Color(255, 204, 0));
        textField238.setName(""); // NOI18N
        textField238.setText("7 yemek kaşığı sebze yemeği");
        jPanel1.add(textField238, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 170, 30));

        textField239.setBackground(new java.awt.Color(70, 70, 70));
        textField239.setForeground(new java.awt.Color(255, 204, 0));
        textField239.setName(""); // NOI18N
        textField239.setText("3 tam ceviz");
        jPanel1.add(textField239, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, 30));

        textField240.setBackground(new java.awt.Color(70, 70, 70));
        textField240.setForeground(new java.awt.Color(255, 204, 0));
        textField240.setName(""); // NOI18N
        jPanel1.add(textField240, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 170, 30));

        textField241.setBackground(new java.awt.Color(70, 70, 70));
        textField241.setForeground(new java.awt.Color(255, 204, 0));
        textField241.setName(""); // NOI18N
        jPanel1.add(textField241, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 170, 30));

        textField242.setBackground(new java.awt.Color(70, 70, 70));
        textField242.setForeground(new java.awt.Color(255, 204, 0));
        textField242.setName(""); // NOI18N
        textField242.setText("2-3 yemek kaşığı yulaf");
        jPanel1.add(textField242, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 170, 30));

        textField243.setBackground(new java.awt.Color(70, 70, 70));
        textField243.setForeground(new java.awt.Color(255, 204, 0));
        textField243.setName(""); // NOI18N
        textField243.setText("Bol yeşillik");
        jPanel1.add(textField243, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, 30));

        textField244.setBackground(new java.awt.Color(70, 70, 70));
        textField244.setForeground(new java.awt.Color(255, 204, 0));
        textField244.setName(""); // NOI18N
        jPanel1.add(textField244, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 170, 30));

        textField245.setBackground(new java.awt.Color(70, 70, 70));
        textField245.setForeground(new java.awt.Color(255, 204, 0));
        textField245.setName(""); // NOI18N
        textField245.setText("50 gram lor peynir");
        jPanel1.add(textField245, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 170, 30));

        textField246.setBackground(new java.awt.Color(70, 70, 70));
        textField246.setForeground(new java.awt.Color(255, 204, 0));
        textField246.setName(""); // NOI18N
        textField246.setText("Bol yeşillikli salata");
        jPanel1.add(textField246, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 170, 30));

        textField247.setBackground(new java.awt.Color(70, 70, 70));
        textField247.setForeground(new java.awt.Color(255, 204, 0));
        textField247.setName(""); // NOI18N
        textField247.setText("Vicdan çorbası (sınırsız)");
        jPanel1.add(textField247, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 170, 30));

        textField248.setBackground(new java.awt.Color(70, 70, 70));
        textField248.setForeground(new java.awt.Color(255, 204, 0));
        textField248.setName(""); // NOI18N
        jPanel1.add(textField248, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 170, 30));

        textField249.setBackground(new java.awt.Color(70, 70, 70));
        textField249.setForeground(new java.awt.Color(255, 204, 0));
        textField249.setName(""); // NOI18N
        textField249.setText("1 küçük elma, 1 küçük muz");
        jPanel1.add(textField249, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 170, 30));

        textField250.setBackground(new java.awt.Color(70, 70, 70));
        textField250.setForeground(new java.awt.Color(255, 204, 0));
        textField250.setName(""); // NOI18N
        jPanel1.add(textField250, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 170, 30));

        textField251.setBackground(new java.awt.Color(70, 70, 70));
        textField251.setForeground(new java.awt.Color(255, 204, 0));
        textField251.setName(""); // NOI18N
        textField251.setText("1 kase yoğurt");
        jPanel1.add(textField251, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 170, 30));

        textField252.setBackground(new java.awt.Color(70, 70, 70));
        textField252.setForeground(new java.awt.Color(255, 204, 0));
        textField252.setName(""); // NOI18N
        textField252.setText("2-3 yemek kaşığı bulgur");
        jPanel1.add(textField252, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 170, 30));

        textField253.setBackground(new java.awt.Color(70, 70, 70));
        textField253.setForeground(new java.awt.Color(255, 204, 0));
        textField253.setName(""); // NOI18N
        textField253.setText("6 yemek kaşığı mercimek yemeği");
        jPanel1.add(textField253, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 170, 30));

        textField254.setBackground(new java.awt.Color(70, 70, 70));
        textField254.setForeground(new java.awt.Color(255, 204, 0));
        textField254.setName(""); // NOI18N
        textField254.setText("1 dilim tam buğday ekmek");
        jPanel1.add(textField254, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 170, 30));

        textField255.setBackground(new java.awt.Color(70, 70, 70));
        textField255.setForeground(new java.awt.Color(255, 204, 0));
        textField255.setName(""); // NOI18N
        textField255.setText("1 küçük muz");
        jPanel1.add(textField255, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 170, 30));

        jLabel2.setBackground(new java.awt.Color(70, 70, 70));
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Program üzerinde uzman bilgisi dahilinde değişiklik yapabilirsiniz.\n\n");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 370, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESİM/icons8-back-30.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel4.setBackground(new java.awt.Color(70, 70, 70));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, 20, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESİM/icons8-information-20.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 20, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESİM/icons8-information-20.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 550, 20, 30));

        jLabel7.setBackground(new java.awt.Color(70, 70, 70));
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("Bu beslenme programı örnek bir menü olup yaş, cinsiyet, boy, kilo, hastalık durumu gibi faktörlerle kişiden kişiye değişebilmektedir.Kronik hastalığınız veya herhangi besine karşı alerjiniz varsa bir uzmana danışıp yeni program oluşturabilirsiniz.\n");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 1300, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1382, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1382, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField36ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // 
        EKRAN2 e3 =new EKRAN2();
        e3.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // Ekran çıkış butonunun kapatılması.
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÖRNEKDİYET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÖRNEKDİYET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÖRNEKDİYET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÖRNEKDİYET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ÖRNEKDİYET().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.TextField textField108;
    private java.awt.TextField textField109;
    private java.awt.TextField textField110;
    private java.awt.TextField textField111;
    private java.awt.TextField textField112;
    private java.awt.TextField textField113;
    private java.awt.TextField textField119;
    private java.awt.TextField textField167;
    private java.awt.TextField textField168;
    private java.awt.TextField textField169;
    private java.awt.TextField textField170;
    private java.awt.TextField textField171;
    private java.awt.TextField textField172;
    private java.awt.TextField textField173;
    private java.awt.TextField textField174;
    private java.awt.TextField textField175;
    private java.awt.TextField textField176;
    private java.awt.TextField textField177;
    private java.awt.TextField textField178;
    private java.awt.TextField textField179;
    private java.awt.TextField textField180;
    private java.awt.TextField textField181;
    private java.awt.TextField textField182;
    private java.awt.TextField textField183;
    private java.awt.TextField textField184;
    private java.awt.TextField textField185;
    private java.awt.TextField textField186;
    private java.awt.TextField textField187;
    private java.awt.TextField textField188;
    private java.awt.TextField textField189;
    private java.awt.TextField textField190;
    private java.awt.TextField textField191;
    private java.awt.TextField textField192;
    private java.awt.TextField textField193;
    private java.awt.TextField textField194;
    private java.awt.TextField textField195;
    private java.awt.TextField textField196;
    private java.awt.TextField textField197;
    private java.awt.TextField textField198;
    private java.awt.TextField textField199;
    private java.awt.TextField textField200;
    private java.awt.TextField textField201;
    private java.awt.TextField textField202;
    private java.awt.TextField textField203;
    private java.awt.TextField textField204;
    private java.awt.TextField textField205;
    private java.awt.TextField textField206;
    private java.awt.TextField textField207;
    private java.awt.TextField textField208;
    private java.awt.TextField textField209;
    private java.awt.TextField textField210;
    private java.awt.TextField textField211;
    private java.awt.TextField textField212;
    private java.awt.TextField textField213;
    private java.awt.TextField textField214;
    private java.awt.TextField textField215;
    private java.awt.TextField textField216;
    private java.awt.TextField textField217;
    private java.awt.TextField textField218;
    private java.awt.TextField textField219;
    private java.awt.TextField textField220;
    private java.awt.TextField textField221;
    private java.awt.TextField textField222;
    private java.awt.TextField textField223;
    private java.awt.TextField textField224;
    private java.awt.TextField textField225;
    private java.awt.TextField textField226;
    private java.awt.TextField textField227;
    private java.awt.TextField textField228;
    private java.awt.TextField textField229;
    private java.awt.TextField textField230;
    private java.awt.TextField textField231;
    private java.awt.TextField textField232;
    private java.awt.TextField textField233;
    private java.awt.TextField textField234;
    private java.awt.TextField textField235;
    private java.awt.TextField textField236;
    private java.awt.TextField textField237;
    private java.awt.TextField textField238;
    private java.awt.TextField textField239;
    private java.awt.TextField textField240;
    private java.awt.TextField textField241;
    private java.awt.TextField textField242;
    private java.awt.TextField textField243;
    private java.awt.TextField textField244;
    private java.awt.TextField textField245;
    private java.awt.TextField textField246;
    private java.awt.TextField textField247;
    private java.awt.TextField textField248;
    private java.awt.TextField textField249;
    private java.awt.TextField textField250;
    private java.awt.TextField textField251;
    private java.awt.TextField textField252;
    private java.awt.TextField textField253;
    private java.awt.TextField textField254;
    private java.awt.TextField textField255;
    private java.awt.TextField textField36;
    private java.awt.TextField textField37;
    // End of variables declaration//GEN-END:variables
}
